### PR TITLE
Even shorter permalinks

### PR DESCRIPTION
**Pull request by gjorquera**
Add permalinks of one word for blog posts.

I realized that having one word as the permalink forces us to keep the blog post
brutally focused on one thing, which is good.

Over the time I will be improving my blog posts content and description to
follow this idea.

With the `jekyll-redirect-from` plugin I will be adding the original medium
permalinks to avoid breaking whatever already exists out there.

### CODE REVIEW

**Comment by maikch** [comment]
Looks good, I only have one issue with this: you'll have posts focuses one thing, which is good, but you'll only have one word to discriminate between posts. Two posts about similar topics might have equal permalinks, which isn't allowed. What should we do in that case?

**Comment by gjorquera** [comment]
Hmmm I'm thinking on several things:

* Use more than one word for the second one.
* If the second blog post talks about two things (I'm not suggesting that every blog post *must be only* about one thing either, just that it should have a clear focus) then use the word for the second focus.
* Use synonyms.
* Worry about it when it happens :smile:.

I feel calmer when looking at these simpler URLs while pasting them or sharing them with people. So, I prefer to assume the cost of handling two blog posts with similar focus if it gives me the benefit of having every other blog post with a simple URL.

**Comment by maikch** [comment]
OK, you're right. It is cooler to have simple URLs.

**Comment by gjorquera** [comment]
Cool! Are we good to merge?

**Comment by maikch** [comment]
Sure, gogogo!

**Pull request merged**
